### ISSUE TITLE
Error: wrong type argument: package-desc, nil

### ISSUE THREAD

**Issue by Saul-BT** [quelpa/quelpa-use-package#14]
Hi, I'm new with quelpa.
I tried to install `manateelazycat/awesome-tray` with quelpa, but I got this error:
`wrong type argument: package-desc, nil`
This is my elisp code:
```
(use-package awesome-tray
      :quelpa (awesome-tray :fetcher github :repo "manateelazycat/awesome-tray"))
;;      :init (awesome-tray-mode 1))
```

Elisp source of `awesome-tray` seems to be downloaded (quelpa/build), but not interpreted :/

**Comment by steckerhalter** [comment]
I get this:

```elisp
Debugger entered--Lisp error: (error "Package lacks a file header")
  signal(error ("Package lacks a file header"))
  error("Package lacks a file header")
  package-buffer-info()
  quelpa-get-package-desc("/home/user/.emacs.d/quelpa/packages/awesome-tray-20200401.1705.el")
```

I think the reason is that `awesome-tray.el` does not have a correct header... it should be three ; so `;;;` but it has only two `;;`:

```elisp
;; awesome-tray.el ---  Modular tray bar
```

Then the emacs function `(package-buffer-info)` fails and cannot get the info it needs. The header should be fixed to correspond to the guidelines: https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html

Cheers

**Comment by steckerhalter** [comment]
The last line is correct, btw:

```elisp
;;; awesome-tray.el ends here
```

**Comment by Saul-BT** [comment]
Oh, thanks for the info @steckerhalter :D
I'll send PR (with the header corrections) to see if the problem is solved

**Comment by Saul-BT** [comment]
[Issue Solved](https://github.com/manateelazycat/awesome-tray/pull/37)
Thanks @steckerhalter

**Comment by steckerhalter** [comment]
:+1:

**Comment by lrustand** [comment]
Please allow fetching packages even if the comments are not in the correct format. I do not have any way of fixing the comments in other peoples packages, so if the comments are wrong then I should be able to just tell quelpa to ignore the error.

**Comment by kiennq** [comment]
I think you can clone other packages that doesn't follow the correct format and fix it there?
Btw, the fetching packages with wrong comments are blocked due to `quelpa` is using `package` to check for that. So, it would need an upstream fix for ignoring the errors

**Comment by alphapapa** [comment]
> Please allow fetching packages even if the comments are not in the correct format. I do not have any way of fixing the comments in other peoples packages, so if the comments are wrong then I should be able to just tell quelpa to ignore the error.

@lrustand It sounds easy when you say it like that, but in practice, handling missing and corrupt metadata is not trivial, because there are often unexpected downstream consequences.  It's not reasonable to expect tools like Quelpa to handle corrupted packages.  The expectations of Elisp libraries are well documented in the ELisp manual, on MELPA, and other places.  It is the responsibility of library authors to follow them.  If some random library you want to use doesn't follow them, there's nothing stopping you from just copying the file into your config and loading it without Quelpa.
